JetBrains/kotlinconf-app

android/app/build.gradle, android/app/src/main/java/com/jetbrains/kotlinconf/ui/InfoFragment.kt, android/app/src/main/java/com/jetbrains/kotlinconf/ui/SessionDetailsFragment.kt, android/app/src/main/java/com/jetbrains/kotlinconf/ui/SessionListFragment.kt, android/app/src/main/java/com/jetbrains/kotlinconf/ui/SessionPagerFragment.kt, android/build.gradle, backend/build.gradle, build.gradle, common-js/build.gradle, common-jvm/build.gradle, common/build.gradle, gradle/wrapper/gradle-wrapper.properties, settings.gradle
* Updated the dependency versions
* Disabled the WEB module for now, its not fully working
=> Upgraded the dependencies

common/src/commonMain/kotlin/org/jetbrains/kotlinconf/presentation/SessionDetailsPresenter.kt
remove duplicated calls to fetch rating from repository
=> Remove unnecessary repository call

.fleet/settings.json, shared/build.gradle.kts, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/components/KCText.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/components/NowLabel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/components/SectionTitle.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/components/StyledText.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/components/SwitcherItem.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/theme/ColorValues.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/theme/Colors.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/theme/PreviewUtil.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/theme/Theme.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui25/theme/Typography.kt
Adding the colors and text styles from the design.
I've also created a couple of simple components with some common previews. These are not meant to be production-ready yet, but they showcase how to access theme values.
=> Add colors and styles, initial drafts of components

ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/DayHeader.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/theme/ColorValues.kt, ui-components/src/jvmMain/kotlin/org/jetbrains/kotlinconf/ui/components/Gallery.kt
=> Add Day Header component

ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/StyledText.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/theme/Colors.kt, ui-components/src/jvmMain/kotlin/org/jetbrains/kotlinconf/ui/components/Gallery.kt
=> Add ServiceEvents component

gradle/libs.versions.toml, ui-components-gallery/src/androidMain/kotlin/org/jetbrains/kotlinconf/android/MainActivity.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/Gallery.kt
- Moves slider to top of gallery
- Adds insets for Android gallery
- Bumps hot reload version to latest
=> Gallery improvements

gradle/libs.versions.toml, kotlin-js-store/yarn.lock, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/Gallery.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Action.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FeedbackForm.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Kodee.kt
Fixes #205 
https://github.com/user-attachments/assets/4ae7c8e6-bb03-4774-94ab-83ac59d4e11e
=> Add FeedbackForm component

ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/Gallery.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ScrollIndicator.kt
Fixes #204 
https://github.com/user-attachments/assets/3057cc6a-43e5-4e76-9212-d86d60aaea5e
=> Add ScrollIndicator component

ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/Gallery.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Divider.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FeedbackForm.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Kodee.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowLabel.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/StyledText.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
Fixes #193 
The `TalkCard` is probably the most complex component in the app. For the time being, I've created it with a long parameter list, individual parameters for every piece of data that it needs to receive. Depending on the data we'll have from other layers, we can certainly adjust this later on to make it more convenient to call.
PR also includes a bunch of small fixes to related components that I ran into while building the Talk Card.
https://github.com/user-attachments/assets/a7d796e2-ebd3-48ca-a7d6-2c031ab1f27c
=> Create TalkCard component

ui-components/src/commonMain/composeResources/values/strings.xml, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FeedbackForm.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Filters.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MainHeader.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowButton.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowLabel.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageTitle.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
Merging the strings changes from https://github.com/JetBrains/kotlinconf-app/pull/211 into `kotlinconf-2025`. Accidentally merged them into this `components-12` branch initially.
=> Extract string resources

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutApp.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/CodeOfConduct.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/PartnerDetails.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Partners.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Schedule.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Session.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Settings.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Speaker.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Speakers.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/TermsOfUse.kt
=> Add stub screens for navigation

shared/src/commonMain/composeResources/files/app-terms.md, shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/Routes.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AppPrivacyPolicy.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AppTermsOfUse.kt
They are separate and different from Visitor's Terms of Use and Privacy Policy
=> App Terms of use and Privacy Policy screens

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/APIClient.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/Routes.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/InfoScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/NewsDetailScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/NewsDetailViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/NewsListScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/NewsListViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/ApplicationStorage.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/MultiplatformSettingsStorage.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MarkdownView.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NetworkImage.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NewsCard.kt
Fixes #265 
We'll need to double-check the UI once the real API response is set up.
https://github.com/user-attachments/assets/6c3c2be2-8262-4040-8f71-8b705747055b
=> Create news screens

androidApp/src/androidMain/kotlin/org/jetbrains/kotlinconf/android/MainActivity.kt, iosApp/iosApp/iOSApp.swift, shared/src/androidMain/kotlin/org/jetbrains/kotlinconf/AndroidNotificationService.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/IOSNotificationService.kt
Android:
https://github.com/user-attachments/assets/9f0d09a0-2c98-4db8-abd0-ffbea529d6d3
iOS:
https://github.com/user-attachments/assets/0ba65e76-1789-4a74-a133-f81f59b31982
=> Navigate to session page when notification is clicked

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/DateTimeFormatting.kt
Addresses the remaining known TODOs on this screen from the previous PR https://github.com/JetBrains/kotlinconf-app/pull/270: 
- Filtering tags being based on real data instead of hardcoded values (still hardcoded, but now updated for 2025)
- Improvements on date and string handling
- State preservation around navigation
Still remaining:
- https://github.com/JetBrains/kotlinconf-app/issues/269
=> Create Schedule screen (part 4)

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
=> Implement service event handling, tweak schedule screen UI

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/StyledText.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
https://github.com/user-attachments/assets/7ed5807a-0025-4837-b42b-4694bec00899
=> Workshop infinite scroller

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/APIClient.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Errors.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionViewModel.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Kodee.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
Some Friday evening fun: added haptic feedback to session voting
Currently, feedback forms are hidden, so you'll need to enable them manually in the code
@zsmb13 could you please check whether these haptics make sense on Android?
=> Improve voting

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/AppInit.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConferenceViewModel.kt
=> Add real values for About Conference screen

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, ui-components/src/commonMain/composeResources/values/strings.xml, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
* Ask "How was the workshop?" in feedback widgets
* Hide pager if only one workshop is available to show
https://github.com/user-attachments/assets/9cbbe1c3-2de0-4d7d-8032-2d2fd1d0a4ad
=> Update workshop related UI

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/PartnerDetailScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt
| | |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/94e1dda3-d91a-4fed-932e-62825d8a0a99) | ![image](https://github.com/user-attachments/assets/0f850aba-ba00-4a8b-b060-54e8659d242b) |
=> Add partner detail screen

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt
=> Keep empty slots with labels if there are no bookmarked sessions in slot

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MainHeader.kt
https://github.com/user-attachments/assets/254e23c6-48c7-4b84-984b-67f11cd00fb4
=> Don't show search clear button on empty input

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/BaseScreens.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AppPrivacyPolicy.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AppTermsOfUse.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/CodeOfConduct.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicenseScreens.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/PrivacyPolicyForVisitors.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/TermsOfUse.kt
https://github.com/user-attachments/assets/af13f7cd-e0f0-4ed4-8928-1b30c5a5d5f9
=> Fix bottom insets

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/Routes.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MapScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
https://github.com/user-attachments/assets/625c4016-dc90-413a-a672-abc8642cbf9b
=> Introduce nested map screen when opened from session details

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutAppScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageTitle.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/StyledText.kt
=> Make titles, names, and descriptions selectable

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Flags.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SettingsScreen.kt, shared/src/jvmMain/kotlin/org/jetbrains/kotlinconf/main.kt
On desktop, skip notification settings in onboarding and don't show notification settings in Settings screen
=> Add flag for notification feature

shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt
=> Improve UIScrollView interop, set alpha to 0

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/SpeakerCard.kt
For consistency in rounding on all screens where it's used
=> Move corner rounding into SpeakerCard component

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Flags.kt, shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/main.ios.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/theme/KotlinConfTheme.kt
=> Add flag for ripples in KotlinConfTheme, disable on iOS

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt
Fixes https://github.com/JetBrains/kotlinconf-app/issues/339
https://github.com/user-attachments/assets/caf1063d-d4aa-4fef-904f-1d4578bfbcf3
=> Add Codelab format to filters, add description to About Conf page

shared/src/commonMain/composeResources/drawable/play_video.xml, shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutAppScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageMenuItem.kt
=> Add "Watch the video" button

androidApp/src/androidMain/kotlin/org/jetbrains/kotlinconf/android/MainActivity.kt
| Before | After |
|--------|--------|
| ![before](https://github.com/user-attachments/assets/005b2704-3fff-4588-8c9b-422b45b14171) | ![after](https://github.com/user-attachments/assets/94d33289-9f22-42db-9113-c73c86b3f748) |
=> Fix three-button nav bar

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt
=> Add "Education" to list of tags

gradle/libs.versions.toml
Recreating #421 because something strange was stuck with that PR
=> Update compose-multiplatform to 1.8.0-beta02 

shared/src/androidMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HideKeyboardOnDragHandler.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt, shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt, shared/src/jvmMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt, shared/src/webMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt
https://github.com/user-attachments/assets/a0bcbed1-c753-473d-b87f-5d39338d7251
=> Show speakers in an adaptive grid

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/AppInit.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicenseScreens.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicensesViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/Search.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
https://github.com/user-attachments/assets/0ee2842d-3c29-42bc-ba3a-4949a5eadd5e
=> Add search to Licenses screen, refactor and optimize searches

androidApp/src/androidMain/kotlin/org/jetbrains/kotlinconf/android/KotlinConfApplication.kt, shared/src/androidMain/kotlin/org/jetbrains/kotlinconf/platformModule.android.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/AppInit.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Flags.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/DeveloperMenuScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/MultiplatformSettingsStorage.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/DebugLogger.kt, shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/main.ios.kt, shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/utils/IOSLogger.kt, shared/src/jsMain/kotlin/org/jetbrains/kotlinconf/main.js.kt, shared/src/jvmMain/kotlin/org/jetbrains/kotlinconf/main.kt, shared/src/jvmMain/kotlin/org/jetbrains/kotlinconf/utils/JvmLogger.kt, shared/src/wasmJsMain/kotlin/org/jetbrains/kotlinconf/main.wasm.kt
=> Add in-memory debug logging flag to dev menu

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HideKeyboardOnDragHandler.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MainHeader.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
=> Only request focus once in feedback fields

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/AppInit.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicenseScreens.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicensesViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersViewModel.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/Search.kt, ui-components/src/commonMain/composeResources/values/strings.xml, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Filters.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
* Move filter into scrollable list
* Show result count on both search screens
https://github.com/user-attachments/assets/466937b4-d784-48d0-8d1f-38f47f550ee1
https://github.com/user-attachments/assets/df6bc73c-239a-4d26-8aa1-66efcaef8c80
=> Improve search and filters

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/BaseScreens.kt
| Before | After |
| --- | --- |
| ![Screenshot 2025-04-16 at 18 18 32](https://github.com/user-attachments/assets/c331842b-8175-4bf3-9113-8ecaf849538e) | ![Screenshot 2025-04-16 at 18 13 21](https://github.com/user-attachments/assets/5f1323ad-4908-48e6-8a3e-7bb7ca7cc953) |
=> Move bottom inset padding into scrollable area in ScreenWithTitle

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HardcodedValues.kt
=> Update Bloomberg partner description

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
Avoids some invalid states returned when first/last visible indices were still -1
https://github.com/user-attachments/assets/404479d9-12f9-464a-80cb-ede9fa9a1ca3
=> Extract and improve now button logic

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
When not in search, scroll to active index on first load.
When in search, scroll to top when entering search or changing the search query.
https://github.com/user-attachments/assets/ae6a2afd-7d54-44f4-8334-e216c01a13ea
=> Fix first scroll logic

ui-components/build.gradle.kts, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MarkdownView.kt
Fixes #444 
See details on 
https://github.com/mikepenz/multiplatform-markdown-renderer/issues/374
https://github.com/mikepenz/multiplatform-markdown-renderer/pull/377
https://github.com/mikepenz/multiplatform-markdown-renderer/pull/381
=> Fix markdown scroll state being lost during navigation

shared/src/commonMain/composeResources/values/strings.xml, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutAppScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/InfoScreen.kt, shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
=> Info screen updates

ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Action.kt, ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
=> Adjust talk card feedback row layout

shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicenseScreens.kt
https://github.com/user-attachments/assets/4308393f-aace-4ca6-b7d2-1b94df0f387f
=> Fix insets on license screens
