JetBrains/kotlinconf-app

- android/app/src/main/java/org/jetbrains/kotlinconf/ui/MainActivity.kt
Use icon without the text when the search is expanded
| Before | After |
| :---: |:---:|
| ![screenshot_1537137248](https://user-images.githubusercontent.com/2514790/45601762-16d07680-ba0a-11e8-9751-76f369991068.png) | ![screenshot_1537137225](https://user-images.githubusercontent.com/2514790/45601761-16d07680-ba0a-11e8-8850-2bfc9caee829.png) |
> Search icon squeezed

- android/app/src/main/java/org/jetbrains/kotlinconf/ui/InfoFragment.kt
- android/app/src/main/java/org/jetbrains/kotlinconf/ui/MainActivity.kt
- android/app/src/main/java/org/jetbrains/kotlinconf/ui/SessionDetailsFragment.kt
- android/app/src/main/res/values/strings.xml
1. Filter sessions by typing to the search view on the main screen (`MainActivity` and `SessionDetailsFragment`)
2. Go to the session details
3. Press back (arrow or keyboard)
4. The displayed logo contains text and it's squashed
Set the logo to the icon-only one when the text in a search query is present. Disable logo visibility on `InfoFragment.kt` and `SessionDetailsFragment.kt`.
| Before | After |
| :---: | :---: |
| ![before](https://user-images.githubusercontent.com/2514790/45853942-3801d180-bd40-11e8-9286-ec7888417938.gif) | ![after](https://user-images.githubusercontent.com/2514790/45853941-3801d180-bd40-11e8-8d82-33af337cd7eb.gif) |
- PR also addresses a comment of @hhariri (https://github.com/JetBrains/kotlinconf-app/pull/32#discussion_r219029046) which I missed before merging …
> Fix logo in the menu

- konfios/Pods/PopupDialog/README.md
README.md:133:0: "Bascially" is a misspelling of "Basically"
README.md:247:101: "appearence" is a misspelling of "appearance"
README.md:281:166: "seperately" is a misspelling of "separately"
README.md:451:30: "compatability" is a misspelling of "compatibility"
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
> konfios/Pods/PopupDialog: fix typos in readme

- android/app/build.gradle
- android/build.gradle
- backend/build.gradle
- build.gradle
The `buildscript {}` block should be used in the root build file only (see [this recent advice](https://discuss.gradle.org/t/multiproject-gradle-seems-to-need-plugin-repository-declared-in-each-subproject/27970/4) from Gradle core dev).
This PR removes all applications of `buildscript {}` from subprojects as recommended.
> build: configure buildscript in root build file only

- .editorconfig
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/CardTag.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FiltersTag.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowButton.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Switcher.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TopMenuButton.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TopMenuTitle.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/theme/PreviewUtil.kt
- Fixes #160 
- Fixes #162 
- Fixes #161 
- Fixes #163 
https://github.com/user-attachments/assets/1269ad2c-a6cd-4cff-9458-3f5ea5e52255
https://github.com/user-attachments/assets/cdb894bb-2b7c-48d9-a4fa-58af158c90e2
> Add second set of components

- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Toggle.kt
This avoids any possible future problems with the .border modifier drawing a white artifact around the edges of the thumb circle
From discussion:
https://kotlinlang.slack.com/archives/CJLTWPH7S/p1732394481077219?thread_ts=1732393581.144109&cid=CJLTWPH7S
> Draw thumb color using a canvas

- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/DayHeader.kt
Combines all nodes of the element so that it's read as one item with screen readers
> Fix DayHeader accessibility

- ui-components/src/commonMain/composeResources/values/strings.xml
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FeedbackForm.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Filters.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MainHeader.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowButton.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/NowLabel.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageTitle.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
> Extract string resources to strings.xml

- shared/src/wasmJsMain/kotlin/org/jetbrains/kotlinconf/main.wasm.kt
- ui-components-gallery/src/wasmJsMain/kotlin/org/jetbrains/kotlinconf/main.wasm.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Speaker.kt
- ui-components/src/wasmJsMain/kotlin/org/jetbrains/kotlinconf/ui/InitCoil.kt
Fixes https://github.com/JetBrains/kotlinconf-app/issues/202, sets up a new version of the Sessionize image proxy that was initially removed in https://github.com/JetBrains/kotlinconf-app/pull/198
> Set up Wasm proxy for Sessionize images

- gradle/libs.versions.toml
- shared/build.gradle.kts
- shared/src/commonMain/composeResources/files/app-privacy-policy.md
- shared/src/commonMain/composeResources/files/visitors-privacy-policy.md
- shared/src/commonMain/composeResources/files/visitors-terms.md
- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/BaseScreens.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/PrivacyPolicyForVisitors.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/StartScreens.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/TermsOfUse.kt
- ui-components/build.gradle.kts
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MarkdownView.kt
There are some minor issues with Markdown rendering (#227), but the screens themselves are ready.
> add General Terms and Conditions and Privacy Policy for visitors screens

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
Moves the Info screen to be the last item of the bottom navigation bar
> Rework order of bottom navigation entries

- gradle/libs.versions.toml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt
Adds the Now button to the header of the screen. Time for the service is now provided by a `TimeProvider`, which has a fake implementation that can put our current time in the middle of the test data from 2024 that we're currently working with.
https://github.com/user-attachments/assets/30e14e31-f26b-4b3e-ae02-42eef67eec20
TODOs remaining on this screen:
- Displaying when a session is coming up soon
- Highlighting workshops in a separate scroller at the top
- Service events
- Filtering tags being based on real data instead of hardcoded values
- Improvements on date and string handling (currently too hardcoded)
- State preservation around navigation
> Create Schedule screen (part 2)

- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionState.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
Adds the following:
- Displaying when a session is coming up soon
- Highlighting workshops in a separate scroller at the top
- Service events (except #269 which will add actual data)
TODOs remaining on this screen:
- #269 
- Filtering tags being based on real data instead of hardcoded values
- Improvements on date and string handling (currently too hardcoded)
- State preservation around navigation
https://github.com/user-attachments/assets/2820a91d-7e7a-4b6d-9e4b-74642d3b2f43
> Create Schedule screen (part 3)

- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/Speakers.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersViewModel.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/Gallery.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/SpeakerCard.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
> implement Speakers screen

- androidApp/src/androidMain/kotlin/org/jetbrains/kotlinconf/android/MainActivity.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/BaseScreens.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/LicenseScreens.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/NewsListScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/PrivacyPolicyScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SettingsScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/StartNotificationsScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/PaddingValues.kt
Tweaks edge-to-edge implementation by adding the appropriate padding on each screen separately. This makes sure that, for example, scrollable content can also fill the entire screen.
https://github.com/user-attachments/assets/1f02b058-0af9-42f2-8e8c-9dda31e2c1c0
> Add per-screen edge-to-edge support

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/ApplicationStorage.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/MultiplatformSettingsStorage.kt
Keep track of current storage version. If we see an older storage version (uninitialized at the moment means it's from before 2025), we destructively migrate to the new version.
Later on, as the storage schema changes, we can create more sophisticated migrations based on the stored and current storage versions.
Fixes [#306](https://github.com/JetBrains/kotlinconf-app/issues/306)
> Add storage versioning

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionViewModel.kt
This loading state will almost never be displayed, as we're loading local data, but it causes some UI glitches that we'd otherwise have to fix
> Remove extra loading state from session detail screen

- androidApp/build.gradle.kts
- build.gradle.kts
- iosApp/KotlinConf.xcodeproj/project.pbxproj
- shared/src/commonMain/composeResources/values/version.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutAppScreen.kt
> Sync versions of apps, add script to update all versions, add version to About screen

- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FeedbackForm.kt
This prevents click listeners above the text field in the hierarchy from triggering when Space or Enter is used
Closes #374
> Consume all key events around feedback form text field

- shared/src/commonMain/composeResources/drawable/play_video.xml
- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/App.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/AppInit.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/ConferenceService.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Flags.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/FlagsManager.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/HideKeyboardOnDragHandler.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/Model.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/TimeProvider.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/KotlinConfNavHost.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/navigation/Routes.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutAppScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/DeveloperMenuScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/ApplicationStorage.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/storage/MultiplatformSettingsStorage.kt
- shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt
- shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/main.ios.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Action.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Filters.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageMenuItem.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
* Fixes scrolling issues caused by the old UIScrollView two-way sync implementation
* Adds a `hideKeyboardOnDrag` flag which, with the bugfix above, should make iOS feedback on the schedule screen work nicely
* Adds a `redirectFeedbackToSessionPage` feature just in case, which replaces in-schedule feedback with navigating the user to the session detail page, to leave their feedback there instead
Hide on drag demo:
https://github.com/user-attachments/assets/7bccfc97-c182-43b5-917b-36d83ea3ddfa
Redirect to session for feedback:
https://github.com/user-attachments/assets/4c23083b-fe56-4c7f-b56d-3bd200b5f9be
> Improve iOS keyboard handling, add feedback and keyboard behavior flags

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/View.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt
* Skips time slots with no sessions in them immediately when they're being created so we don't have to remove these later
* Improves the "Now" concept with `firstActiveIndex` / `lastActiveIndex`, making sure we point "Now" to the current live or the next upcoming session when the time is somewhere within the conference (even if that's the next day)
* Puts lightning talks at the ends of time slots
> Update session handling logic

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/SessionCardView.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/utils/DateTimeFormatting.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
* In talk cards, show the date for sessions on the speaker detail screen and when the schedule is being searched.
* Show the end time of sessions on the session detail screen
> Time display fixes

- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AboutConference.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/AppPrivacyPolicyPrompt.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/CodeOfConduct.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SessionScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SettingsScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt
- ui-components/src/commonMain/composeResources/values/strings.xml
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/DayHeader.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ErrorLoading.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Filters.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/FiltersTag.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/MainHeader.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/PageTitle.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/SettingsItem.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Switcher.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/TalkCard.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Toggle.kt
First patch of accessibility improvements. They consist of the following:
- Adding a couple of content descriptions that were missing/incorrectly set.
- Adding state descriptions for component benefitting from them.
- Annotating headers for easier navigation for screen reader (and other assistive tech utilizing them) users
- Marking errors as live regions so that they'd be announced
- Changing some `clickable` modifiers to `selectable` or `toggleable` to match the semantics to the usage of the element
- Fixing some issues with large text (see example below)
In general, the other changes are about the semantics changing + some tab stops disappearing, the only UI change is the privacy policy screen's scrollability:
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td><video …
> Accessibility improvements

- gradle.properties
- shared/build.gradle.kts
GCC: Gradle Configuration Cache will increase hot reload speeds
Local Build Cache: Will help with switching branches
> Enable Gradle Caching (GCC, and build-cache)

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakerDetailScreen.kt
Fix the issue where the padding was previously applied outside of the scrollable area. The content now correctly reaches the top toolbar when scrolled:
https://github.com/user-attachments/assets/7b740bac-7bac-4aea-9bcc-2f9abde7c872
Modifier ordering is hard
> Fix padding on speaker detail screen

- gradle/libs.versions.toml
Mostly to remove the extra UUID library dependency from our dependency graph, as Koin now uses the stdlib UUID instead
> Update Koin to 4.1.0-Beta7

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/StartNotificationsScreen.kt
- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/ServiceEvents.kt
This PR adds some more semantics (headings & merges service items into one block), and adds correct semantics for the workshop carousel. 
For some reason, the `HorizontalPager` and its child items don't have the correct list semantics, so I added `collectionItemInfo` and `collectionInfo` to them. And even if everything worked as expected with `HorizontalPager`, there's a problem with the page count; now it has `Int.MAX_SIZE` as the size of the list of items (`pageCount`), so instead of the seven items the list has, `Int.MAX_SIZE` would be announced. These changes fix that as well.
> A11y: Carousel semantics

- shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/ScrollToTopHandler.kt
The `UIScrollView` triggers `scrollViewDidScroll` when it's first created, just to signal its initial 0 state. If we already an had existing scroll position (for example, we're navigating back to a previous screen that uses this handler), this forces us to scroll back to the top.
This change ignores this first `scrollViewDidScroll` invocation so that we don't reset state when we shouldn't.
> Fix unnecessary scrolls-to-top

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/MainScreen.kt
Navigating from anything back to the Schedule tab counts as a pop transition, and shows up as a fade on iOS. Here we'll just remove all navigations between tabs on all platforms. This is aligned with popular apps even for Android - they just don't have predictive back animations for these tabbed screens.
> Disable all transitions across Main screen tabs

- shared/src/commonMain/composeResources/values/strings.xml
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/DeveloperMenuScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleScreen.kt
- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/ScheduleViewModel.kt
Updated spacing between days in the schedule:
---
Sorting: past sessions at the end of search results, instead of sorted by time
---
New title for session detail pages, simply "Session":
> Various design fixes

- iosApp/iosApp/iOSApp.swift
- shared/build.gradle.kts
- shared/src/iosMain/kotlin/org/jetbrains/kotlinconf/IOSNotifications.kt
This PR removes the export of the kmpnotifier library in the iOS framework generation.
`IOSNotifications.kt` file in the `iosMain` source set already handles iOS notifications using Kotlin. Exporting `kmpnotifier` library for use on the Swift side is unnecessary. All notification-related logic can be managed within the kotlin side.
> Remove `KmpNotifier` library export from iOS source set

- shared/src/commonMain/kotlin/org/jetbrains/kotlinconf/screens/SpeakersScreen.kt
Animation differs slightly from the original implementation, but it is still good.
> fix speakers list overscrolling on top shortly after switching from some other screen

- ui-components/src/commonMain/kotlin/org/jetbrains/kotlinconf/ui/components/Action.kt
Before | After
--- | ---
Fixes #525
> Fix text sizing in the Action component

- gradle/libs.versions.toml
- shared/build.gradle.kts
Removes this warning when running the desktop app
```
SLF4J(W): No SLF4J providers were found.
SLF4J(W): Defaulting to no-operation (NOP) logger implementation
SLF4J(W): See https://www.slf4j.org/codes.html#noProviders for further details.
```
> Add slf4j-nop dependency for desktop app
